version: '3.8'

services:
  web-server:
    build: .
    container_name: lpl-mcp-web-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    networks:
      - lpl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lpl-network:
    driver: bridge 