name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build Docker image
        run: |
          cd LPL-MCP/Repository/WebService
          docker build -t inventory-api-test .

      - name: Run tests in Docker (with coverage)
        run: |
          docker run --rm -v ${{ github.workspace }}/LPL-MCP/Repository/WebService:/app inventory-api-test \
            pytest --cov=inventory_api --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: LPL-MCP/Repository/WebService/coverage.xml 